### ISSUE TITLE
Group packages together

### ISSUE THREAD

**Issue by hougesen** [hougesen/opad#21]
A config file for grouping multiple packages to the same version.

It could be something like this:

```toml
[group.backend]
version = "0.1.2"
members = ["package1/package.json", "package2/Cargo.toml"]


[group.frontend]
version = "1.0.9"
members = ["package3/package.json", "package4/pubspec.yaml"]
```

The usage could be with a command like `opad sync`.
